# Generated by Django 5.2.1 on 2025-06-11 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glider_id', models.CharField(max_length=100, unique=True)),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('u', models.FloatField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('precise_lat', models.FloatField(blank=True, null=True)),
                ('precise_lon', models.FloatField(blank=True, null=True)),
                ('precise_time', models.DateTimeField(blank=True, null=True)),
                ('glider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_data', to='VisualizeMultipleGliders.glider')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('salinity', models.FloatField(blank=True, null=True)),
                ('oxygen', models.FloatField(blank=True, null=True)),
                ('cdom', models.FloatField(blank=True, null=True)),
                ('chlorophyll', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('glider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_data', to='VisualizeMultipleGliders.glider')),
            ],
        ),
    ]
