# Generated by Django 5.2.1 on 2025-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glider',
            old_name='deployment_date',
            new_name='dateCreated',
        ),
        migrations.AddField(
            model_name='glider',
            name='contributors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='endOfCoverage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='startOfCoverage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
