# Generated by Django 5.2.1 on 2025-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0002_rename_deployment_date_glider_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glider',
            name='operator',
        ),
        migrations.AddField(
            model_name='glider',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
