# Generated by Django 5.2.1 on 2025-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0003_remove_glider_operator_glider_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glider',
            name='dateCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glider',
            name='endOfCoverage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glider',
            name='startOfCoverage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
