# Generated by Django 5.2.1 on 2025-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0004_alter_glider_datecreated_alter_glider_endofcoverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='scientificdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='scientificdata',
            name='precise_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
