# Generated by Django 5.2.1 on 2025-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0005_remove_computerdata_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerdata',
            name='precise_lat',
        ),
        migrations.RemoveField(
            model_name='computerdata',
            name='precise_lon',
        ),
        migrations.RemoveField(
            model_name='computerdata',
            name='precise_time',
        ),
        migrations.AddField(
            model_name='scientificdata',
            name='precise_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientificdata',
            name='precise_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
