# Generated by Django 5.2.1 on 2025-07-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeMultipleGliders', '0006_remove_computerdata_precise_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificdata',
            name='glider',
        ),
        migrations.CreateModel(
            name='Glider_Research_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('salinity', models.FloatField(blank=True, null=True)),
                ('oxygen', models.FloatField(blank=True, null=True)),
                ('cdom', models.FloatField(blank=True, null=True)),
                ('chlorophyll', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('precise_lat', models.FloatField(blank=True, null=True)),
                ('precise_lon', models.FloatField(blank=True, null=True)),
                ('precise_time', models.DateTimeField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('u', models.FloatField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('glider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Glider_Research_Data', to='VisualizeMultipleGliders.glider')),
            ],
        ),
        migrations.DeleteModel(
            name='ComputerData',
        ),
        migrations.DeleteModel(
            name='ScientificData',
        ),
    ]
